import { Inter } from 'next/font/google';

import { Sidebar } from '../components/Sidebar';
import { Header } from '../components/Header';

import './globals.css';
import { HeroPattern } from '../components/HeroPattern';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-zinc-900">
        <Sidebar />

        <div className="relative ml-80 h-screen">
          <Header />

          <HeroPattern />

          <div className="mx-auto max-w-4xl py-24 px-8">{children}</div>
        </div>
      </body>
    </html>
  );
}
